environment:
    matrix:
    - nodejs_version: "12"
install:
    - ps: Install-Product node $env:nodejs_version
    - yarn
    - psql createdb testdb
test_script:
    - node --version
    - yarn test
build: off
services:
  - postgresql10
