environment:
    matrix:
    - nodejs_version: "12"
install:
    - ps: Install-Product node $env:nodejs_version
    - yarn
test_script:
    - node --version
    - yarn test
build: off
build_script:
  - createdb testdb
services:
  - postgresql10
